apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sap-assignment03
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # frequency of metric collection
    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:9080']
      - job_name: 'request-service'
        static_configs:
          - targets: ['request-service:9081']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: sap-assignment03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.11.2
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: sap-assignment03
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090